stages:
  - build
  - test
  - deploy

variables:
  PHP_VERSION: "8.2"  # Version de PHP à utiliser

build-job:
  stage: build
  image: php:8.2-apache  # Utilisation d'une image Docker PHP
  script:
    - echo "Construction de l'image Docker"
    # Construction de l'image Docker à partir du Dockerfile
    - docker build -t zoojose:latest .

test-job:
  stage: test
  image: php:$PHP_VERSION  # Utilisation d'une image Docker PHP
  script:
    - echo "Tests de l'application"
    # Démarrage d'un conteneur Docker à partir de l'image construite
    - docker run --name mon_app_test zoojose:latest php ./tests/test.php

deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application"  # Ajoutez les commandes de déploiement ici
    # Exemple: déploiement sur un serveur distant avec SSH
    - ssh user@server "cd /path/to/app && git pull origin master"
    # Ajoutez d'autres commandes de déploiement ici
  environment:
    name: production
    url: https://example.com  # URL de l'environnement de production
