cache:
  paths:
    - vendor/

stages:
  - build
  - test
  - deploy

variables:
  PHP_VERSION: "8.2"  # Version de PHP à utiliser
  docker_image: "docker:stable"
  IMAGE_APP: "zoojose:latest"

build-image:
  stage: build
  image: $docker_image
  services:
    - docker:dind
  script:
    - echo "Construction de l'image Docker"
    # Construction de l'image Docker à partir du Dockerfile
    - docker build -t $IMAGE_APP . --file Dockerfile
    # Sauvegarde de l'image dans un fichier archive;
    - docker save -o image.tar $IMAGE_APP
  artifacts:
    paths:
      - image.tar

build-job:
  stage: test
  image: $docker_image
  services:
    - docker:dind
  script:
    - echo "Chargement de l'image Docker"
    # Chargement de l'image Docker construite précédemment
    - docker load -i image.tar
    # Démarrage des services avec Docker Compose
    - docker-compose up -d
    # Affichage des conteneurs en cours d'exécution pour vérification
    - docker ps -a
    - docker exec db_zoo tail -f /var/log/mysql/error.log
    - docker exec ZooJose php ./vendor/bin/phpunit tests
  before_script:
    # Installez Docker Compose
    - apk update && apk add docker-compose
  after_script:


deploy-job:
  stage: deploy
  script:
    - echo "Déploiement de l'application"  # Ajoutez les commandes de déploiement ici
    # Exemple: déploiement sur un serveur distant avec SSH
    - ssh user@server "cd /path/to/app && git pull origin master"
    # Ajoutez d'autres commandes de déploiement ici
  environment:
    name: production
    url: https://example.com  # URL de l'environnement de production
