version: '2.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: zoojose
    container_name: ZooJose
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/ZooJose
      PDO_HOST: db
      PDO_USER: admin
      PDO_PASSWORD: 1234
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`zoo.bertil.re`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.apps.tls=true"
      - "traefik.http.routers.apps.tls.certresolver=cloudflare"
      - "traefik.http.routers.apps.entrypoints=websecure"
      - "traefik.http.routers.apps.rule=Host(`zoo.bertil.re`)"
      # Indique à Traefik le port interne sur lequel le service écoute (ici 80)
      - "traefik.http.services.app.loadbalancer.server.port=80"
      - "traefik.docker.network=webTraefik"  # Réseau Docker utilisé par Traefik
    depends_on:
      - db
      - mongo
    networks:
      - webTraefik
  db:
    image: mysql:latest
    container_name: db_zoo
    restart: always
    volumes:
      # espace memoire pour mysql
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: jose
      MYSQL_DATABASE: db_zoo
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - webTraefik
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - webTraefik
volumes:
  db-data:

networks:
  webTraefik:
    external: true
