version: '2.3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: zoojose
    container_name: ZooJose
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/ZooJose
      PDO_HOST: db
      PDO_USER: admin
      PDO_PASSWORD: 1234
    ports:
      - "8888:80"
    depends_on:
      - db
      - mongo
    networks:
      - dev
  db:
    image: mysql:latest
    container_name: db_zoo
    restart: always
    volumes:
      # espace memoire pour mysql
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: jose
      MYSQL_DATABASE: db_zoo
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - dev
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - dev
volumes:
  db-data:

networks:
  dev:
