DROP TABLE IF EXISTS service ;
DROP TABLE IF EXISTS avis ;
DROP TABLE IF EXISTS rapport_veterinaire_annimaux CASCADE ;
DROP TABLE IF EXISTS rapport_employe_animal CASCADE ;
DROP TABLE IF EXISTS animal_image CASCADE;
DROP TABLE IF EXISTS animal CASCADE ;
DROP TABLE IF EXISTS rapport_employe CASCADE ;
DROP TABLE IF EXISTS rapport_veterinaire CASCADE ;
DROP TABLE IF EXISTS utilisateur CASCADE ;
DROP TABLE IF EXISTS role CASCADE ;
DROP TABLE IF EXISTS habitat_image CASCADE ;
DROP TABLE IF EXISTS image CASCADE ;
DROP TABLE IF EXISTS habitat CASCADE ;
DROP TABLE IF EXISTS race CASCADE ;

